import type { Metadata } from 'next'
import './globals.css'
import { poppins } from './fonts'
import { TailwindIndicator } from '@/components/ui/tailwind-indicator'

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
      <TailwindIndicator />
    </html>
  )
}
